### ISSUE TITLE
Change in function bits for relay is ignored by server

### ISSUE THREAD

**Issue by klew** [SUPLA/supla-core#142]
Currently server remembers relay function bits send by the device during first registration. If those bits are changed later, server ignores such change.
This may be problematic, because the only workaround for this problem that I found is to remove device from server and register it again.
Problem may appear when i.e. there are some channels with history on the same device and when some new relay function will be added in new version of software. Then after software update on device, new relay function will not be available untill device is removed from server and whole measurements history is lost.

**Comment by przemyslawzygmunt** [comment]
Duplicate
