### ISSUE TITLE
Add heat meter support for the impulse counter channel type

### ISSUE THREAD

**Issue by przemyslawzygmunt** [SUPLA/supla-core#145]
#define SUPLA_CHANNELFNC_IC_HEAT_METER 340

**Comment by klew** [comment]
GJ?  Maybe some option to select betwen GJ and kWh?
kWh seems to be used more frequently in home related usage.

**Comment by przemyslawzygmunt** [comment]
GJ is more common in some meters, and kWh in others. The pulse counter allows you to enter your own unit.
