### ISSUE TITLE
Supla protocol docs

### ISSUE THREAD

**Issue by jfedyczak** [SUPLA/supla-core#17]
I'm trying to use Zamel ROW-01 module with my own server. I know that device connects to port 2016 with TLS secured connection. Is there any documentation on the protocol being used?

**Comment by przemyslawzygmunt** [comment]
There is no documentation available now.
You must read source files:

https://github.com/SUPLA/supla-core/blob/master/supla-common/proto.c
https://github.com/SUPLA/supla-core/blob/master/supla-common/proto.h
https://github.com/SUPLA/supla-core/blob/master/supla-common/srpc.c
https://github.com/SUPLA/supla-core/blob/master/supla-common/srpc.h

**Comment by magx2** [comment]
Do you have in plans to create some docs? Right now this is the biggest missing point. Without this is hard for new developers to join this project. On first glance not having docs looks like purposeful obfuscating code.
