### ISSUE TITLE
Introduce integration with Yandex Voice Assistant

### ISSUE THREAD

**Issue by przemyslawzygmunt** [SUPLA/supla-core#183]

**Comment by Pavelkpactu** [comment]
hi, everyone!
We have popular Voice Assistant from Yandex (most popular than Google and Alexa, in Russia)
They have API for integrate Oauth2 services into their app store.
i'll try use this instuctions: https://github.com/SUPLA/supla-cloud/wiki/Integrations
but got massage from cloud.supla.org/Oauth-authorize  - "could not find your account"

Can you help me? I didn't find yandex's github project, but they have them-self help: https://yandex.ru/dev/dialogs/alice/doc/smart-home/concepts/quick-start.html/

I can contact their programmers.

![1](https://user-images.githubusercontent.com/56015343/101024791-a8921300-3585-11eb-9d28-6633080033c8.PNG)
![2](https://user-images.githubusercontent.com/56015343/101024808-acbe3080-3585-11eb-934a-0138c0501858.PNG)
![3](https://user-images.githubusercontent.com/56015343/101024812-afb92100-3585-11eb-89bd-80f2cccef415.PNG)

**Comment by RusaBel** [comment]
> hi, everyone!
> We have popular Voice Assistant from Yandex (most popular than Google and Alexa, in Russia)

> всем привет!
> У нас есть популярный голосовой помощник от Яндекса (самый популярный, чем Google и Alexa, в России)
> У них есть API для интеграции сервисов Oauth2 в свой магазин приложений.
> я попробовал использовать эти инстукции: [](https://github.com/SUPLA/supla-cloud/wiki/Integrations)
> https://github.com/SUPLA/supla-cloud/wiki/Integrations но получил массаж от cloud.supla.org/Oauth-authorize - "не удалось найти ваш аккаунт"
> 
> Вы не могли бы мне помочь? Я не нашел проект яндекса github, но у них есть-самопомощь: https://yandex.ru/dev/dialogs/alice/doc/smart-home/concepts/quick-start.html/
> 
> Я могу связаться с их программистами.

Hi, is there any result in the attempts to link the supla and yandex accounts? I have now come to the conclusion that I absolutely need it.

**Comment by przemyslawzygmunt** [comment]
This functionality is pending implementation.

**Comment by przemyslawzygmunt** [comment]
[#idinahuj](https://twitter.com/hashtag/idinahuj)
