### ISSUE TITLE
SUPLA_DEVICE_FLAG_CALCFG_ENTER_CFG_MODE flag support

### ISSUE THREAD

**Issue by przemyslawzygmunt** [SUPLA/supla-core#215]

**Comment by przemyslawzygmunt** [comment]
https://github.com/SUPLA/supla-cloud/issues/448

**Comment by fracz** [comment]
> może warto po stronie urządzeń dodać jakiś timeout - np. 5-10 min - jeśli nie było żadnego połączenia do AP ?
