### ISSUE TITLE
Add screen in app and web where you can enter numeric value and got 2-3 buttons (for example: turning on and off device in specified classroom, displaying queue info in public places)

### ISSUE THREAD

**Issue by domin746826** [SUPLA/supla-core#289]

**Comment by przemyslawzygmunt** [comment]
More details please.

**Comment by domin746826** [comment]
For example if you have any Thermometer sensor in device then in mobile app it shows icon, label "temperature" and numeric value with "°C". In Thermometer element you can go in something like "advanced" settings in mobile app and there are icon, value and temperature history. I would like to have numeric displayer like "general purpose measurement" but when you go advanced settings you can enter value using numeric keyboard and send it

How it could look 
![mainScreen](https://user-images.githubusercontent.com/52156158/165686994-813253f9-af2f-4298-8627-987792ba1fa4.jpg)
![settingsScreen](https://user-images.githubusercontent.com/52156158/165686998-868f3dd4-f1f0-4507-aa76-bc63c033059b.jpeg)

btw general purpose measurement doesn't work on arduino/esp8266 (I know it's not listed in supported sensors on its repo but it would be nice to have it working, presenting numeric data using Thermometer class or similar works but doesn't look good because of "°C")

**Comment by klew** [comment]
"General purpose measurement" is not implmeneted yet. It shouldn't be working now.

**Comment by domin746826** [comment]
And what about the number input from keyboard?

**Comment by przemyslawzygmunt** [comment]
Data entry from the client application is not planned.
