### ISSUE TITLE
Implement as an option the cancellation of the gate closing / opening task by the opening sensor.

### ISSUE THREAD

**Issue by przemyslawzygmunt** [SUPLA/supla-core#306]
https://forum.supla.org/viewtopic.php?p=127680#p127680

**Comment by przemyslawzygmunt** [comment]
By the way, implement loading the certificate into memory so as not to read it from the file each time.

**Comment by fracz** [comment]
Opcja dodana dla `CONTROLLINGTHEGATE` i `CONTROLLINGTHEGARAGEDOOR` - 20 i 30.

`stateVerificationMethodActive: true/false`

**Comment by przemyslawzygmunt** [comment]
stateVerificationMethodActive
