### ISSUE TITLE
TOGGLE action

### ISSUE THREAD

**Issue by fracz** [SUPLA/supla-core#65]

**Comment by klew** [comment]
Should it be still open? There is toggle action for light and power switch available on cloud.

**Comment by fracz** [comment]
Yes, becuase Cloud emulates the toggle now (it checks the state first and sends appropriate command to the server). There is no TOGGLE action supported by the core.

**Comment by klew** [comment]
I noticed that cloud is quite lazy in updating state (it takes few seconds to update), and it selects on or off action depending on state stored locally on cloud.
As a result it can send "off" value to device, when it in fact was already "off".

**Comment by klew** [comment]
Is it planned to implement it on server/core? Or also on device level?
