### ISSUE TITLE
openssl 1.0.0?

### ISSUE THREAD

**Issue by 6Xkljk8Vj7Tk1k4** [SUPLA/supla-core#7]
[root@dev Release]# ./supla-server -h
./supla-server: /lib64/libcrypto.so.1.0.0: version `OPENSSL_1.0.0' not found (required by ./supla-server)
./supla-server: /lib64/libssl.so.1.0.0: version `OPENSSL_1.0.0' not found (required by ./supla-server)

openssl for CentOS 7 cant be downgraded to 1.0.0 

1.0.0 has been discontinued upstream by openssl and it is lacking fixes for the last many high severity openssl vulnerabilities. Do you plan to support new openssl ?

**Comment by przemyslawzygmunt** [comment]
cd /usr/src
sudo mkdir openssl
sudo wget https://www.openssl.org/source/openssl-1.0.1t.tar.gz
sudo tar zxvf openssl-1.0.1t.tar.gz
cd openssl-1.0.1t
sudo ./config --prefix=/usr/src/openssl shared
*edit Makefile and remove no-ssl2 flags
sudo make depend
sudo make install
sudo cp /usr/src/openssl/lib/*.so /usr/lib/supla-server/
sudo rm -rf cp /usr/src/openssl

**Comment by przemyslawzygmunt** [comment]
cd /usr/src
git clone https://github.com/SUPLA/supla-core
cd supla-core/supla-server/Release

https://github.com/SUPLA/supla-core/blo ... kefile#L47

replace to:
g++ -L/usr/include/mysql -L/usr/src/openssl/lib -pthread -lrt -o "supla-server" $(OBJS) $(USER_OBJS) $(LIBS)

https://github.com/SUPLA/supla-core/blo ... dir.mk#L99

replace to:
g++ -D__OPEN_SSL=1 -I/usr/include/mysql -I/usr/src/openssl/include -O3 -Wall -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.d)" -o "$@" "$<"

https://github.com/SUPLA/supla-core/blo ... ir.mk#L106

replace to:
gcc -O3 -Wall -I/usr/src/openssl/include -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.d)" -o "$@" "$<"


then 
cd Release
make clean && make

cp supla-server /usr/sbin/

**Comment by przemyslawzygmunt** [comment]
Or just recompile your master openssl library with sslv2 enabled
